default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # In format postgres://username:password@host:port/db
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
